apiVersion: apps/v1
kind: Deployment
metadata:
  name: ihwa-liao-dev
spec:
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: ihwa-liao-dev
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ihwa-liao-dev
    spec:
      enableServiceLinks: false
      containers:
        - name: ihwa-liao-dev
          image: ghcr.io/seankhliao/ihwa-liao-dev
          ports:
            - name: http
              containerPort: 8080
          startupProbe:
            httpGet:
              path: /-/ready
              port: http
          livenessProbe:
            httpGet:
              path: /-/ready
              port: http
          readinessProbe:
            httpGet:
              path: /-/ready
              port: http
