apiVersion: v1
kind: Service
metadata:
  name: ihwa-liao-dev
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 8080
  selector:
    app.kubernetes.io/name: ihwa-liao-dev
