apiVersion: skaffold/v4beta5
kind: Config
metadata:
  name: ihwa
build:
  artifacts:
    - image: ghcr.io/seankhliao/ihwa
      ko:
        env:
          - CGO_ENABLED=0
        ldflags:
          - -s
          - -w
  tagPolicy:
    inputDigest: {}
  platforms:
    - linux/amd64
    - linux/arm64
manifests:
  kustomize:
    paths:
      - manifests
deploy:
  kubectl: {}
